# if you have not been home for a long time

- alias: Включити світло на кухні при відкритті дверей
  trigger:
    - platform: state
      entity_id: binary_sensor.door_kitchen
      to: 'on'
  condition:
    - condition: state
      entity_id: person.sated
      state: 'not_home'
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.person.sated.last_changed)) / 3600 > 2 }}"
  action:
    - service: light.turn_on
      entity_id: light.lamps
  mode: single

  